/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dumpfmuff' at '30.12.16 12:00' with Gradle 2.11
 *
 * @author dumpfmuff, @date 30.12.16 12:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
